### ISSUE TITLE
refactor(configuration): Move accounts & locations definitions to resourceType level

### ISSUE THREAD

**Issue by jeyrschabu** [spinnaker/swabbie#106]
Current:
```
providers:
    - name: aws
      locations:
        - us-east-1
        - us-west-2
      accounts:
        - test
        - prod
```
Future:
```
resourceTypes:
  - name: image
     enabled: false
     .
     .
     accounts:
       - test
       - prod
      locations:
       - us-east-1
       - us-west-2
```
This should allow more fine grained control on how to scope swabbie actions for a resource type. Instead of relying on exclusions on accounts.
